ls:
  src:
    .dir: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | kebab-case
    .js: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase
    .ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase
    .d.ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase
    .spec.js: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase
    .stories.js: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase
